### ISSUE TITLE
Is it possible to add default commands

### ISSUE THREAD

**Issue by niuiic** [JoshMcguigan/estream#7]
hi，thank you for your great job, and it helps me a lot. But it feels a bit troublesome to enter the compile command every time.

I try to execute the command when vim starts, but there is nothing when I open the quickfix window. Also try to change `command -nargs=1 Async execute "AsyncRun <args>` to `command -nargs=1 Async execute "AsyncRun make`，but it seems to be causing an error。

**Comment by JoshMcguigan** [comment]
Thanks for the feedback! 

For default commands, I’d set that up with a mapping in vimrc. 

As for the other question, I’m not sure I follow exactly what your issue is. Also I don’t use estream much anymore so I won’t be able to provide too much feedback.

**Comment by niuiic** [comment]
Ok, thank you. Maybe I can try to implement this feature by myself. And I will close this issue.
